spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8080

  datasource:
    url: jdbc:mysql://localhost:3307/userservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
